# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0f471b17755acd9ce37c1b190a32663d84d689e525f0669afe91adcdf97b6694cfcdee6571af69273c50e481c5e4804c09da1ef93d0d67567dd97dd74f23dc3

test:
  secret_key_base: e008581527681b1c3c4d340620cca230d2bd03dc76d55f2a798125f63a18d9e62d034940eeb923415d5cbe1d518eed6b5718577c69235e3370e27ce2f55fb053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
